/* File generated with Shader Minifier 1.1.6
 * http://www.ctrl-alt-test.fr
 */
#ifndef FRAG_DRAW_H_
# define FRAG_DRAW_H_
# define VAR_FRAGCOLOR "v"
# define VAR_IFRAME "y"
# define VAR_IRESOLUTION "m"

const char *draw_frag =
 "#version 430\n"
 "layout(location=0)out vec4 v;"
 "layout(location=0)uniform vec4 m;"
 "layout(location=1)uniform int y;\n"
 "#define sat(a)clamp(a,0.,1.)\n"
 "#define PI 3.14159265\n"
 "mat2 x(float v)"
 "{"
   "float y=cos(v),x=sin(v);"
   "return mat2(y,-x,x,y);"
 "}"
 "float t(float v)"
 "{"
   "return mod(sin(v*123.457)*123.456,1.);"
 "}"
 "vec3 t(vec3 v,vec2 y)"
 "{"
   "float m=1.35;"
   "vec3 x=normalize(cross(v,vec3(0.,1.,0.))),z=normalize(cross(v,x));"
   "return normalize(v+m*(x*y.x+z*y.y));"
 "}"
 "vec2 x(vec2 v,vec2 y)"
 "{"
   "if(v.x<y.x)"
     "return v;"
   "return y;"
 "}"
 "float t(vec3 v,vec3 x,vec3 y)"
 "{"
   "vec3 f=abs(v)-x;"
   "float z=max(max(f.x,f.y),f.z);"
   "f=abs(f)-y;"
   "float m=max(f.y,f.z),n=max(f.x,f.z),l=max(f.x,f.y);"
   "return max(min(min(m,n),l),z);"
 "}"
 "float n(vec3 v,vec3 y)"
 "{"
   "vec3 f=abs(v)-y;"
   "return max(f.x,max(f.y,f.z));"
 "}"
 "float f;"
 "float n()"
 "{"
   "return f++,t(f);"
 "}"
 "float n(vec3 v,vec3 y,float x)"
 "{"
   "return v=mod(v+y*.5,y)-y*.5,min(length(v.xy)-x,min(length(v.xz)-x,length(v.yz)-x));"
 "}"
 "vec2 n(vec3 v)"
 "{"
   "vec2 f=vec2(10000.,-1.);"
   "vec3 y=v,z=vec3(.5),m=floor((y+z*.5)/z);"
   "y=mod(y+z*.5,z)-z*.5;"
   "y+=sin(m)*.2;"
   "float s=(sin(m.x+m.z+m.y)*.5+.5)*.1;"
   "f=x(f,vec2(length(y)-.01+s,-2.));"
   "f=x(f,vec2(length(v)-1.,0.));"
   "vec3 l=v,e=vec3(1.),d=5.*e;"
   "l=max(-d*.5,l);"
   "l=min(d*.5,l);"
   "vec3 a=floor((l+e*.5)/e);"
   "l=mod(l+e*.5,e)-e*.5;"
   "vec3 i=vec3(.5)*sign(sin(a*vec3(2.,3.,4.)));"
   "float c=mod(a.x+11.*a.y+a.z*2.,2.),r=mix(n(l,vec3(.5)),length(l+i)-1.,c),o=n(v,d-d*.5);"
   "r=max(r,n(l,vec3(.485)));"
   "r=mix(r,100.,mod(a.y+mod(a.x+a.z,2.),2.));"
   "r=max(r,o);"
   "if(c==1.)"
     "c+=mod(a.x,2.);"
   "f=x(f,vec2(r,c));"
   "float g=t(l,vec3(.5),vec3(.001))+.007;"
   "g=max(g,o);"
   "f=x(f,vec2(g,-2.));"
   "float P=-v.y+d.y*.5+.007;"
   "f=x(f,vec2(P,-1.));"
   "return f;"
 "}"
 "vec3 s(vec3 v,float y)"
 "{"
   "vec2 f=vec2(.01,0.);"
   "return normalize(vec3(y)-vec3(n(v-f.xyy).x,n(v-f.yxy).x,n(v-f.yyx).x));"
 "}"
 "vec3 s(vec3 v,vec3 m,int y)"
 "{"
   "vec3 f=v;"
   "for(int z=0;z<y&&distance(f,v)<30.;++z)"
     "{"
       "vec2 l=n(f);"
       "if(l.x<.01)"
         "return vec3(l.x,distance(f,v),l.y);"
       "f+=m*l.x*.4;"
     "}"
   "return vec3(-1.);"
 "}"
 "vec3 n(vec3 v,vec3 y,vec3 x,vec3 f)"
 "{"
   "vec3 m=y*.5+.5,l=normalize(vec3(1.,-1.,1.));"
   "float z=sat(dot(l,y));"
   "if(f.z==-1.)"
     "m=vec3(.1)*z;"
   "if(f.z==-2.)"
     "m=vec3(1.);"
   "if(f.z==0.)"
     "m=vec3(.2)*z;"
   "if(f.z>0.)"
     "m=mix(vec3(1.),vec3(1.,0.,0.),f.z-1.);"
   "m=m.xxx;"
   "m=mix(m,m*vec3(.988,.29,.325),1.-sat((abs(v.z)-1.)*100.));"
   "return m;"
 "}"
 "vec3 s(vec2 v)"
 "{"
   "vec3 f=vec3(0.);"
   "float y=6.;"
   "vec3 m=vec3(y,1,-y),l=vec3(0.,1.5,0.),r=normalize(l-m);"
   "vec2 z=(vec2(n(),n())-.5)*.1;"
   "m.xy+=z*3.;"
   "r.xy-=z*.45;"
   "r=t(r,v);"
   "vec3 a=s(m,r,256);"
   "float x=100.;"
   "if(a.y>0.)"
     "{"
       "x=a.y;"
       "vec3 g=m+r*a.y,e=s(g,a.x);"
       "f=n(g,e,r,a);"
       "vec3 d=normalize(reflect(r,e)+(vec3(n(),n(),n())-.5)*.05),c=s(g+e*.01,d,128);"
       "if(c.y>0.)"
         "{"
           "vec3 P=g+e*.01+d*c.y,o=s(P,c.x);"
           "f+=n(P,o,d,c)*vec3(.439,.459,1.);"
         "}"
     "}"
   "vec3 d=vec3(.604,.071,.71);"
   "f=mix(f,2.*mix(d.xxx,d,.5)*(1.-sat(abs(v.x*2.))),1.-exp(-x*.017));"
   "return f;"
 "}"
 "vec3 e(vec2 v)"
 "{"
   "vec2 f=normalize(vec2(1.))*.01*sat(length(v));"
   "vec3 m=vec3(0.);"
   "float z=mod(float(y),3.);"
   "m.x=s(v+f).x;"
   "m.y=s(v).y;"
   "m.z=s(v-f).z;"
   "return m;"
 "}"
 "void main()"
 "{"
   "vec2 z=gl_FragCoord.xy/m.xy,l=(gl_FragCoord.xy-.5*m.xy)/m.xx;"
   "f=float((y*73856093^int(gl_FragCoord.x)*19349663^int(gl_FragCoord.y)*83492791)%38069);"
   "vec3 x=pow(e(l),vec3(1.5))*1.5;"
   "x+=pow(s(l+(vec2(n(),n())-.5)*.1),vec3(2.));"
   "x=sat(x);"
   "vec2 r=vec2(1.,-1.)/(m.x*1.5);"
   "x=sat(x);"
   "v=vec4(x,1.);"
 "}";

#endif // FRAG_DRAW_H_
