/* File generated with Shader Minifier 1.1.6
 * http://www.ctrl-alt-test.fr
 */
#ifndef FRAG_DRAW_H_
# define FRAG_DRAW_H_
# define VAR_FRAGCOLOR "f"
# define VAR_IFRAME "v"
# define VAR_IRESOLUTION "m"

const char *draw_frag =
 "#version 430\n"
 "layout(location=0)out vec4 f;"
 "layout(location=0)uniform vec4 m;"
 "layout(location=1)uniform int v;"
 "const float a=acos(-1.);"
 "mat2 t(float v)"
 "{"
   "float a=cos(v),n=sin(v);"
   "return mat2(a,-n,n,a);"
 "}"
 "float t(vec3 v,float f)"
 "{"
   "return(dot(abs(v),vec3(1))-f)/sqrt(3.);"
 "}"
 "float n(vec3 v)"
 "{"
   "float f=t(v,1.5);"
   "v.y=abs(v.y)-.15;"
   "f=max(f,-t(v,1.5));"
   "return f;"
 "}"
 "vec3 n(vec3 v,float f)"
 "{"
   "return mod(v-f,f+f)-f;"
 "}"
 "float s(vec3 v)"
 "{"
   "float f=1e+09,a=4.;"
   "for(int r=0;r<3;++r)"
     "f=min(f,n(n(v+vec3(a,0,a),a))),f=min(f,n(n(v+vec3(0,a,0),a))),v=v.yzx;"
   "return f;"
 "}"
 "float r;"
 "float n()"
 "{"
   "float v=fract(r++*.1031);"
   "v+=v*(v+19.19)*3.;"
   "return fract((v+v)*v);"
 "}"
 "vec2 s()"
 "{"
   "return vec2(n(),n());"
 "}"
 "void main()"
 "{"
   "r=float((v*73856093^int(gl_FragCoord.x)*19349663^int(gl_FragCoord.y)*83492791)%38069);"
   "vec2 n=(gl_FragCoord.xy+s()-.5)/m.xy-.5;"
   "n.x*=m.z;"
   "n*=4.+length(n);"
   "vec3 l=vec3(0,0,-10),z=normalize(vec3(n,1));"
   "vec2 c=(s()-.5)*t(a*.25);"
   "const float i=.5,y=17.;"
   "l.xy+=c*i;"
   "z.xy-=c*i/y;"
   "l.yz*=t(atan(1.,sqrt(2.)));"
   "z.yz*=t(atan(1.,sqrt(2.)));"
   "l.xz*=t(a*.75);"
   "z.xz*=t(a*.75);"
   "vec3 g=vec3(.2*length(n),.1,.25);"
   "const float x=.001;"
   "float e=0.,d=0.;"
   "for(int o=0;o<200;++o)"
     "{"
       "d=s(l+z*e);"
       "if(abs(d)<x)"
         "break;"
       "e+=d;"
     "}"
   "if(abs(d)<x)"
     "{"
       "vec3 o=l+z*e;"
       "vec2 u=vec2(x,0);"
       "vec3 b=normalize(vec3(s(o+u.xyy),s(o+u.yxy),s(o+u.yyx))-d);"
       "float F=dot(b,normalize(vec3(1,2,3)))*.35+.65,p=min(1.,pow(.9,e-20.));"
       "g=mix(g,vec3(F),p);"
     "}"
   "f=vec4(g,1);"
 "}";

#endif // FRAG_DRAW_H_
